version: 2

builds:
  - id: ttp-clock-sync
    skip: true

release:
  prerelease: auto
  extra_files:
    - glob: ./release-artifacts/*

changelog:
  use: git
  sort: asc
  groups:
    - title: Features
      regexp: '^feat(\(.+\))?!?:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix(\(.+\))?!?:'
      order: 1
    - title: Performance Improvements
      regexp: '^perf(\(.+\))?!?:'
      order: 2
  filters:
    exclude:
      - '^docs(\(.+\))?!?:'
      - '^style(\(.+\))?!?:'
      - '^refactor(\(.+\))?!?:'
      - '^test(\(.+\))?!?:'
      - '^build(\(.+\))?!?:'
      - '^ci(\(.+\))?!?:'
      - '^chore(\(.+\))?!?:'
      - '^revert(\(.+\))?!?:'
      - '^Merge'
